/*
 * Port_PBcfg.c
 *
 *  Created on: Jul 22, 2022
 *      Author: mustafa
 */
#include "Port.h"

const Port_ConfigType Port_Configuration [PORT_NUM_PORT_PIN] =
{
   PORT_PIN_DEFAULT_CONFIG,
   PORT_PIN_DEFAULT_CONFIG,
   PORT_PIN_DEFAULT_CONFIG,
   PORT_PIN_DEFAULT_CONFIG,
   PORT_PIN_DEFAULT_CONFIG,
   PORT_PIN_DEFAULT_CONFIG,
   PORT_PIN_DEFAULT_CONFIG,
   PORT_PIN_DEFAULT_CONFIG,
   PORT_PIN_DEFAULT_CONFIG,
   PORT_PIN_DEFAULT_CONFIG,
   PORT_PIN_DEFAULT_CONFIG,
   PORT_PIN_DEFAULT_CONFIG,
   PORT_PIN_DEFAULT_CONFIG,
   PORT_PIN_DEFAULT_CONFIG,
   PORT_PIN_DEFAULT_CONFIG,
   PORT_PIN_DEFAULT_CONFIG,
   PORT_PIN_DEFAULT_CONFIG,
   PORT_PIN_DEFAULT_CONFIG,
   PORT_PIN_DEFAULT_CONFIG,
   PORT_PIN_DEFAULT_CONFIG,
   PORT_PIN_DEFAULT_CONFIG,
   PORT_PIN_DEFAULT_CONFIG,
   PORT_PIN_DEFAULT_CONFIG,
   PORT_PIN_DEFAULT_CONFIG,
   PORT_PIN_DEFAULT_CONFIG,
   PORT_PIN_DEFAULT_CONFIG,
   PORT_PIN_DEFAULT_CONFIG,
   PORT_PIN_DEFAULT_CONFIG,
   PORT_PIN_DEFAULT_CONFIG,
   PORT_PIN_DEFAULT_CONFIG,
   PORT_PIN_DEFAULT_CONFIG,
   PORT_PIN_DEFAULT_CONFIG,
   PORT_PIN_DEFAULT_CONFIG,
   PORT_PIN_DEFAULT_CONFIG,
   PORT_PIN_DEFAULT_CONFIG,
   PORT_PIN_DEFAULT_CONFIG,
   PORT_PIN_DEFAULT_CONFIG,
   PORT_PIN_DEFAULT_CONFIG,
   PORT_PIN_SW2_CONFIG,
   PORT_PIN_LED_RED_CONFIG,
   PORT_PIN_LED_BLUE_CONFIG,
   PORT_PIN_LED_GREEN_CONFIG,
   PORT_PIN_SW1_CONFIG
};
